service:
  flush: 1
  log_level: debug
  http_server: on
  http_port: ${FLUENT_BIT_HTTP_MONITORING_PORT}

pipeline:
  inputs:
    - name: dummy
      samples: 1
      dummy: |
        {
         "message:": "something",
         "spanid": "251484295a9df731",
         "trace_id": {
            "w3c": "63560bd4d8de74fae7d1e4160f2ee099"
         },
         "traceid": "63560bd4d8de74fae7d1e4160f2ee099"
        }

  outputs:
    - name: stdout
      match: '*'

    - name: opentelemetry
      match: '*'
      host: 127.0.0.1
      port: ${TEST_SUITE_HTTP_PORT}
      logs_uri: /v1/logs
      logs_body_key: $message
      logs_trace_id_message_key: $traceid
      logs_span_id_message_key: $spanid
