service:
  flush: 1
  log_level: info
  http_server: on
  http_port: ${FLUENT_BIT_HTTP_MONITORING_PORT}
pipeline:
  inputs:
    - name: splunk
      port: ${FLUENT_BIT_TEST_LISTENER_PORT}
      host: 0.0.0.0
      http2: on
      net.keepalive: on
      tls: on
  outputs:
    - name: stdout
      match: '*'
