service:
  flush: 1
  log_level: info
  http_server: on
  http_port: ${FLUENT_BIT_HTTP_MONITORING_PORT}
pipeline:
  inputs:
    - name: splunk
      port: 9883
      host: 0.0.0.0
      http2: off
      net.keepalive: on
      tls: on
      tls.crt_file: ../certificate/certificate.pem
      tls.key_file: ../certificate/private_key.pem
  outputs:
    - name: stdout
      match: '*'
